//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperationsPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketHistory
    {
        public int TicketHistoryId { get; set; }
        public int TicketId { get; set; }
        public Nullable<int> PreviousTicketStatusId { get; set; }
        public int NewTicketStatusId { get; set; }
        public int ChangedByUserId { get; set; }
        public string Comment { get; set; }
        public System.DateTime ChangedAt { get; set; }
    
        public virtual User User { get; set; }
        public virtual TicketStatu TicketStatu { get; set; }
        public virtual TicketStatu TicketStatu1 { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
