//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperationsPortal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.TicketHistories = new HashSet<TicketHistory>();
        }
    
        public int TicketId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int OpenedByUserId { get; set; }
        public Nullable<int> AssignedToUserId { get; set; }
        public int CategoryId { get; set; }
        public int TicketStatusId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketHistory> TicketHistories { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual TicketStatu TicketStatu { get; set; }
    }
}
